apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edu03-dev

resources:
- ../../base

patches:
- path: ./deployment-patch.yaml
  target:
    kind: Deployment
- path: ./ingress-patch.yaml
  target:
    kind: Ingress

images:
- name: ktdseduacr.azurecr.io/edu03/samplejava
  newName: ktdseduacr.azurecr.io/edu03/samplejava
  newTag: v20251020162246

